import type {
  BaselineAssessment,
  BaselinePrompt,
  ConstraintProfile,
  FrameworkTemplate,
  GrowthMapItem,
  KnowledgeDatabase,
  LanguageProfile,
  MissionCardData,
  PortfolioProfile,
  PracticePrompt,
  ProjectProfile,
  QuestionBankItem,
  ResumeProfile,
  RoleTemplate,
  StrategyTemplate,
  TargetCompany,
  TargetJob,
  UploadIntakeOption,
  UserProfile,
  VaultDocument,
} from './types'

export const dimensionLabels = {
  career_positioning: '职业定位清晰度',
  cv_portfolio_support: '简历 / 作品集支撑',
  project_storytelling: '项目叙事能力',
  ai_product_application: 'AI / 产品应用能力',
  language_expression: '面试表达语言',
  role_fit: '岗位匹配表达',
  pressure_handling: '压力追问处理',
  evidence_integrity: '证据完整度',
} as const

export const irsWeights = {
  career_positioning: 10,
  cv_portfolio_support: 10,
  project_storytelling: 20,
  ai_product_application: 20,
  language_expression: 15,
  role_fit: 10,
  pressure_handling: 10,
  evidence_integrity: 5,
} as const

export const seedUser: UserProfile = {
  user_id: 'user_seed_001',
  name: '示例候选人',
  current_stage: '第 1 阶段 - 暖场准备',
  education_background: 'AI 相关研究生背景，可在设置中替换',
  career_background:
    '具备工业设计基础，经历过硬件产品、消费电子、可持续方向与 AI 项目探索，当前目标是转向 AI 产品与智能硬件产品岗位。',
  target_roles: ['AI 产品经理', '智能硬件 / AIoT 产品经理'],
  target_locations: ['香港', '深圳', '广州'],
  target_markets: ['AI 应用', '智能硬件', '项目型产品'],
  daily_available_time: 180,
  job_search_strategy: '保守暖场策略',
  constraints: ['避免高频出差岗位', '优先产品侧 owner 机会', '训练必须留下证据'],
  preferred_language: '中文 + 英文',
  created_at: '2026-06-02T00:00:00.000Z',
  updated_at: '2026-06-02T00:00:00.000Z',
}

export const strategyTemplates: StrategyTemplate[] = [
  {
    id: 'conservative',
    name: '保守暖场策略',
    summary: '先用 C 类练手机会拿真实反馈，再进入 B 类主投池，等准备度提升后再冲 A 类目标。',
    cadence: '每次 A 类目标模拟前，至少完成 3 次练习面试',
  },
  {
    id: 'balanced',
    name: '均衡投递策略',
    summary: '小批量混合 C/B/A 机会，同时保持每日训练节奏，避免答案系统失稳。',
    cadence: '每轮 1 个 C、2 个 B、1 个 A',
  },
  {
    id: 'target-sprint',
    name: '目标公司冲刺',
    summary: '集中攻一个高价值公司或岗位，减少泛化练习，把训练聚焦到 JD、项目深挖和公司场景。',
    cadence: '公司简报、JD 拆解、项目深挖、定向模拟',
  },
  {
    id: 'urgent',
    name: '快速落地策略',
    summary: '优先落地速度和现金流稳定，但仍然保留训练证据，避免只靠海投。',
    cadence: '每日 B/C 投递 + 短时定向练习',
  },
]

export const roleTemplates: RoleTemplate[] = [
  {
    role_template_id: 'rt_ai_pm',
    role_name: 'AI 产品经理',
    role_category: 'AI 产品',
    core_competencies: ['AI 工作流设计', 'MVP 范围控制', '评估指标定义', '用户问题拆解'],
    common_question_types: ['AI 知识应用', '产品 Case', '项目深挖'],
    scoring_weights: { ai_product_application: 30, project_storytelling: 25, role_fit: 20 },
    recommended_frameworks: ['AI 知识五步', '产品 Case', '项目 7 步'],
    training_modules: ['用项目场景解释 RAG', 'AI 功能评估', '产品 MVP 取舍'],
  },
  {
    role_template_id: 'rt_aiot_pm',
    role_name: '智能硬件 / AIoT 产品经理',
    role_category: '智能硬件',
    core_competencies: ['软硬件取舍', 'NPI 意识', '场景设计', '风险协调'],
    common_question_types: ['项目深挖', '压力追问', '产品 Case'],
    scoring_weights: { project_storytelling: 30, role_fit: 20, pressure_handling: 15 },
    recommended_frameworks: ['项目 7 步', '压力追问', '产品 Case'],
    training_modules: ['硬件产品故事', '传感器到洞察场景', '制造约束追问'],
  },
  {
    role_template_id: 'rt_product_project',
    role_name: '产品 / 项目经理',
    role_category: '产品交付',
    core_competencies: ['范围控制', '干系人对齐', '时间线清晰', '结果衡量'],
    common_question_types: ['行为面试', '项目深挖', '压力追问'],
    scoring_weights: { project_storytelling: 25, pressure_handling: 20, evidence_integrity: 15 },
    recommended_frameworks: ['STAR-LF', '项目 7 步', '压力追问'],
    training_modules: ['跨职能冲突故事', '决策记录复盘', '结果指标修补'],
  },
  {
    role_template_id: 'rt_solution_npi',
    role_name: '解决方案 / NPI / 供应链项目经理',
    role_category: '解决方案交付',
    core_competencies: ['方案映射', '客户约束理解', 'NPI 流程', '交付风险'],
    common_question_types: ['项目深挖', '产品 Case', '压力追问'],
    scoring_weights: { role_fit: 25, project_storytelling: 25, pressure_handling: 20 },
    recommended_frameworks: ['项目 7 步', '产品 Case', '压力追问'],
    training_modules: ['客户需求翻译', 'NPI 里程碑模拟', '风险升级回答'],
  },
  {
    role_template_id: 'rt_design_to_product',
    role_name: 'UX / 工业设计转产品',
    role_category: '设计转产品',
    core_competencies: ['用户洞察', '作品集证据', '产品逻辑', '设计到商业翻译'],
    common_question_types: ['项目深挖', '行为面试', '产品 Case'],
    scoring_weights: { cv_portfolio_support: 25, project_storytelling: 25, role_fit: 20 },
    recommended_frameworks: ['项目 7 步', 'STAR-LF', '产品 Case'],
    training_modules: ['设计决策转产品指标', '作品集故事压缩', '可迁移能力匹配'],
  },
  {
    role_template_id: 'rt_graduate',
    role_name: '通用管培 / 应届岗位',
    role_category: '应届与管培',
    core_competencies: ['领导力', '学习敏捷度', '沟通表达', '问题解决'],
    common_question_types: ['行为面试', '压力追问', '反问环节'],
    scoring_weights: { language_expression: 20, pressure_handling: 20, career_positioning: 15 },
    recommended_frameworks: ['STAR-LF', '压力追问'],
    training_modules: ['宝洁式领导力故事', '学习成长证据', '高质量反问'],
  },
  {
    role_template_id: 'rt_english_interview',
    role_name: '外企英文面试',
    role_category: '语言与文化',
    core_competencies: ['英文自我介绍', '简洁项目说明', '追问处理', '反向提问'],
    common_question_types: ['英文追问', '行为面试', '压力追问'],
    scoring_weights: { language_expression: 35, role_fit: 20, pressure_handling: 15 },
    recommended_frameworks: ['STAR-LF', '项目 7 步', '压力追问'],
    training_modules: ['英文自我介绍', '追问修补', '简洁反问'],
  },
]

export const baselineAssessment: BaselineAssessment = {
  assessment_id: 'assess_seed_001',
  user_id: seedUser.user_id,
  date: '2026-06-02',
  overall_irs: 64,
  dimension_scores: {
    career_positioning: 68,
    cv_portfolio_support: 62,
    project_storytelling: 58,
    ai_product_application: 61,
    language_expression: 64,
    role_fit: 67,
    pressure_handling: 59,
    evidence_integrity: 72,
  },
  top_weaknesses: ['项目叙事能力', '压力追问处理', 'AI / 产品应用能力'],
  recommended_bootcamp_days: 7,
  recommended_strategy: '保守暖场策略',
}

export const resumeProfiles: ResumeProfile[] = [
  {
    resume_id: 'resume_seed_001',
    user_id: seedUser.user_id,
    title: 'AI 产品方向简历',
    language: '中文',
    target_role_type: 'AI 产品经理',
    content: '可替换的简历档案，包含项目证据、产品转型叙事和岗位匹配重点。',
    uploaded_file_status: '已上传',
    parsed_status: '已解析',
    indexed_status: '已索引',
    last_updated: '2026-06-02',
  },
]

export const portfolioProfiles: PortfolioProfile[] = [
  {
    portfolio_id: 'portfolio_seed_001',
    user_id: seedUser.user_id,
    title: '产品作品集档案',
    type: '网页作品集',
    url: 'https://example.com/portfolio',
    content_summary: '可替换的作品集摘要，包含项目故事、结果和证据链接。',
    uploaded_file_status: '已上传',
    parsed_status: '已解析',
    indexed_status: '需要刷新',
    last_updated: '2026-06-02',
  },
]

export const projectProfiles: ProjectProfile[] = [
  {
    project_id: 'project_seed_001',
    user_id: seedUser.user_id,
    title: '项目 1：AI 面试训练 MVP',
    project_type: 'AI 产品 MVP',
    role: '产品 owner / 设计负责人',
    background: '一个可配置的 AI 产品场景，用户需求模糊，训练目标需要被量化。',
    user_or_business_problem: '用户需要的是可被追问检验的面试证据，而不是被动刷资料后的心理安慰。',
    key_decisions: ['定义可衡量的准备度', '保留训练证据', '把真实面试复盘反哺题库'],
    solution: '用资料库、摸底、训练、模拟面试和真实复盘构成闭环训练流。',
    result: 'Seed data 可以演示完整训练闭环，同时不把系统写死给某一个人。',
    reflection: '后续真实检索和 AI 评分可以替换当前模拟逻辑，不需要推翻前端数据模型。',
    transferable_skills: ['问题定义', 'AI 工作流设计', 'MVP 范围控制'],
    related_role_templates: ['rt_ai_pm', 'rt_design_to_product'],
    evidence_links: ['本地 seed 证据'],
    indexed_status: '已索引',
  },
  {
    project_id: 'project_seed_002',
    user_id: seedUser.user_id,
    title: '项目 2：智能硬件概念',
    project_type: '智能硬件概念',
    role: '研究与产品设计',
    background: '一个带有物理约束的软硬件结合产品案例。',
    user_or_business_problem: '需要把设备约束翻译成产品决策，并变成面试中讲得清楚的故事。',
    key_decisions: ['把用户场景和技术特性分开', '展示取舍', '记录可衡量结果'],
    solution: '用项目 7 步把设计过程转译成产品岗位证据。',
    result: '可用于 AIoT、NPI 和项目经理类面试。',
    reflection: '在冲 A 类岗位前，还需要补强量化结果。',
    transferable_skills: ['硬件产品取舍', '用户洞察', '跨职能沟通'],
    related_role_templates: ['rt_aiot_pm', 'rt_solution_npi'],
    evidence_links: ['Seed 证据'],
    indexed_status: '已解析',
  },
]

export const targetCompanies: TargetCompany[] = [
  {
    company_id: 'company_seed_001',
    user_id: seedUser.user_id,
    company_name: '星曜 AI 实验室',
    industry: 'AI 应用',
    company_type: 'AI 原生产品公司',
    location: '香港',
    company_summary: '用于测试公司定向模拟面试流程的示例目标公司。',
    source_url: '模拟来源',
    notes: '准备度达到 88+ 后再作为 A 类目标冲刺。',
  },
  {
    company_id: 'company_seed_002',
    user_id: seedUser.user_id,
    company_name: '北辰智能设备',
    industry: '智能硬件',
    company_type: '硬件与 AIoT 公司',
    location: '深圳',
    company_summary: '用于验证智能硬件产品匹配度的 B 类示例公司。',
    source_url: '模拟来源',
    notes: '适合用来验证项目故事是否站得住。',
  },
  {
    company_id: 'company_seed_003',
    user_id: seedUser.user_id,
    company_name: '练习产品工作室',
    industry: '产品服务',
    company_type: '面试暖场机会',
    location: '广州',
    company_summary: '用于练习真实反馈的 C 类示例机会。',
    source_url: '模拟来源',
    notes: '可用于拿反馈，不消耗 A 类机会。',
  },
]

export const targetJobs: TargetJob[] = [
  {
    job_id: 'job_seed_001',
    user_id: seedUser.user_id,
    company_id: 'company_seed_001',
    role_title: 'AI 产品经理',
    role_template_id: 'rt_ai_pm',
    city: '香港',
    job_type: '全职',
    level: '初级到中级',
    salary_range: '市场区间',
    jd_text: '设计 AI 工作流，定义评估指标，并把模糊的用户需求转化为可落地 MVP。',
    job_status: '已保存目标',
    abc_level: 'A',
    application_status: '准备度达标后投递',
    risk_tags: ['需要精准 AI 产品案例', '大概率有英文追问'],
    resume_version: 'AI 产品 v1',
    readiness_score: 72,
    next_action: 'IRS 达到 80+ 后再跑公司定向模拟',
    notes: '高价值目标；答案系统稳定前不要急投。',
  },
  {
    job_id: 'job_seed_002',
    user_id: seedUser.user_id,
    company_id: 'company_seed_002',
    role_title: '智能硬件产品经理',
    role_template_id: 'rt_aiot_pm',
    city: '深圳',
    job_type: '全职',
    level: '初级到中级',
    salary_range: '市场区间',
    jd_text: '负责智能设备场景、软硬件取舍和跨职能交付。',
    job_status: '主投池',
    abc_level: 'B',
    application_status: '正在打磨简历匹配',
    risk_tags: ['NPI 故事还需补强', '可能追问硬件取舍'],
    resume_version: 'AIoT v1',
    readiness_score: 79,
    next_action: '用项目 2 做项目 7 步练习',
    notes: '适合主投池验证。',
  },
  {
    job_id: 'job_seed_003',
    user_id: seedUser.user_id,
    company_id: 'company_seed_003',
    role_title: '产品项目协调',
    role_template_id: 'rt_product_project',
    city: '广州',
    job_type: '全职',
    level: '入门',
    salary_range: '练习区间',
    jd_text: '协调产品需求、时间线和干系人沟通。',
    job_status: '暖场',
    abc_level: 'C',
    application_status: '可用于练习',
    risk_tags: ['战略匹配度较低'],
    resume_version: '通用产品 v1',
    readiness_score: 83,
    next_action: '用于暖场面试反馈',
    notes: 'C 是策略标签，不是岗位好坏评价。',
  },
]

export const languageProfiles: LanguageProfile[] = [
  {
    user_id: seedUser.user_id,
    language: '英文',
    current_level: '准备后可以回答',
    target_level: '稳定处理追问',
    weakness_tags: ['简洁自我介绍', '压力追问', '指标词汇'],
    latest_score: 64,
    practice_count: 8,
  },
  {
    user_id: seedUser.user_id,
    language: '中文',
    current_level: '母语',
    target_level: '结构化产品表达',
    weakness_tags: ['证据顺序', '结果指标'],
    latest_score: 78,
    practice_count: 12,
  },
]

export const constraintProfile: ConstraintProfile = {
  user_id: seedUser.user_id,
  cannot_accept: ['高频出差实施岗', '纯编码岗位', '没有产品 ownership'],
  prefer: ['AI 产品落地', '智能硬件场景', '清晰导师或产品团队'],
  salary_floor: '可配置',
  commute_limit: '可配置',
  overtime_tolerance: '中',
  travel_tolerance: '低',
  location_preference: ['香港', '深圳', '广州'],
}

export const missionCards: MissionCardData[] = [
  {
    id: 'mission_self_intro',
    title: '录一版英文自我介绍',
    why: '这是最快暴露岗位匹配表达弱点的方式，避免真实初筛时才发现问题。',
    minutes: 35,
    evidence: '语音回答 + 模拟转写 + 30 秒修正版',
    linked_practice: '自我介绍',
  },
  {
    id: 'mission_project_story',
    title: '用项目 7 步重建一个项目',
    why: '当前项目故事容易先讲功能，缺少用户问题、个人决策和可衡量结果。',
    minutes: 55,
    evidence: '3 分钟语音讲解 + 转写修正 + 缺失指标清单',
    linked_practice: '项目故事',
  },
  {
    id: 'mission_rag_restate',
    title: '用目标岗位场景解释 RAG',
    why: 'AI 产品岗位考的是应用、风险和评估，不只是概念定义。',
    minutes: 45,
    evidence: '口头费曼复述 + 岗位场景应用 + 风险指标',
    linked_practice: '知识复述',
  },
]

export const warningItems = [
  '今天训练完成前，不要重构作品集结构。',
  '不要把“我看过”当成“我能在追问下讲清楚”。',
  '准备度证据低于阈值时，不要急着投 A 类目标。',
  '不要用新增无关功能来逃避真正的练习。',
]

export const frameworkTemplates: FrameworkTemplate[] = [
  {
    id: 'star_lf',
    name: 'STAR-LF',
    question_type: '行为面试',
    steps: ['情境', '任务', '行动', '结果', '学习', '岗位匹配'],
    best_for: ['领导力', '冲突', '失败', '说服', '团队协作'],
    correction_prompt: '讲完结果后，把故事明确扣回目标岗位。',
  },
  {
    id: 'project_7_steps',
    name: '项目 7 步',
    question_type: '项目深挖',
    steps: ['背景', '用户 / 业务问题', '我的角色', '关键决策', '方案', '结果', '反思与岗位迁移'],
    best_for: ['项目', '作品集', '案例', 'ownership'],
    correction_prompt: '先讲问题和个人贡献，再讲功能细节。',
  },
  {
    id: 'ai_knowledge',
    name: 'AI 知识五步',
    question_type: 'AI / 产品知识',
    steps: ['定义', '机制', '应用', '风险', '指标'],
    best_for: ['RAG', 'Agent', 'LLM', '幻觉', '评估'],
    correction_prompt: '把概念落到一个用户场景，并说明成功标准。',
  },
  {
    id: 'product_case',
    name: '产品 Case',
    question_type: '产品 Case',
    steps: ['目标', '用户', '场景', '方案', 'MVP', '指标', '取舍'],
    best_for: ['MVP', '优先级', '功能', '产品设计'],
    correction_prompt: '说清楚 MVP 里不做什么，以及为什么不做。',
  },
  {
    id: 'pressure',
    name: '压力追问',
    question_type: '压力问题',
    steps: ['承认现实', '重构问题', '拿出证据', '连接岗位价值'],
    best_for: ['转型', '短板', '薪资', '语言差距'],
    correction_prompt: '先简短承认现实，再回到证据和岗位价值。',
  },
]

export const baselinePrompts: BaselinePrompt[] = [
  {
    id: 'baseline_cn_intro',
    type: '中文自我介绍',
    question: '请用 90 秒做一版中文自我介绍，重点说清楚你现在要转向的岗位和证据。',
    time_limit_seconds: 90,
    language: '中文',
  },
  {
    id: 'baseline_en_intro',
    type: '英文自我介绍',
    question: 'Please introduce yourself for an AI product role in 90 seconds.',
    time_limit_seconds: 90,
    language: '英文',
  },
  {
    id: 'baseline_transition',
    type: '转型原因',
    question: '为什么从设计 / 硬件 / 项目经历转向 AI 产品岗位？请讲出动机、证据和风险控制。',
    time_limit_seconds: 120,
    language: '中文',
  },
  {
    id: 'baseline_project',
    type: '关键项目讲解',
    question: '请用 3 分钟讲一个关键项目，按照问题、角色、决策、结果、迁移来讲。',
    time_limit_seconds: 180,
    language: '中文',
  },
  {
    id: 'baseline_ai',
    type: 'AI/产品知识',
    question: '请解释 RAG 在面试训练系统中的作用，并说明如何判断它是否真的提升训练质量。',
    time_limit_seconds: 150,
    language: '中文',
  },
  {
    id: 'baseline_pressure',
    type: '压力题',
    question: '你没有非常线性的 AI 产品背景，为什么我们还应该继续面试你？',
    time_limit_seconds: 120,
    language: '中文',
  },
]

export const practicePrompts: PracticePrompt[] = [
  {
    type: '自我介绍',
    question: '请用 90 秒为 AI 产品岗位做一版自我介绍，并明确说明岗位匹配点。',
    framework: 'STAR-LF',
    time_limit_seconds: 90,
    source_map: {
      personal: '个人资料库：简历、作品集、自我介绍草稿',
      market: '岗位市场库：AI 产品岗位高频要求',
      knowledge: '面试知识库：STAR-LF 开场结构',
      real: '真实面试库：自我介绍常见开场题',
    },
    next_task: '重录 30 秒版本，把岗位匹配句放在第 1 句。',
  },
  {
    type: '项目故事',
    question: '请用 3 分钟讲一个项目，重点说明用户 / 业务问题、你的角色、关键决策、结果，以及如何迁移到目标岗位。',
    framework: '项目 7 步',
    time_limit_seconds: 180,
    source_map: {
      personal: '个人资料库：项目 1 与项目 2 证据',
      market: '岗位市场库：ownership、指标、跨职能要求',
      knowledge: '面试知识库：项目七步法',
      real: '真实面试库：项目深挖题',
    },
    next_task: '把项目答案压缩成 2 分钟版本，并补一个量化结果。',
  },
  {
    type: '知识复述',
    question: '请解释 RAG 如何支持基于简历、JD 和公司资料的定制化面试题生成，并说明如何降低幻觉。',
    framework: 'AI 知识五步',
    time_limit_seconds: 150,
    source_map: {
      personal: '个人资料库：AI 面试训练 MVP 项目',
      market: '岗位市场库：AI 产品经理 JD 高频关键词',
      knowledge: '面试知识库：AI 知识五步',
      real: '真实面试库：AI 概念落地追问',
    },
    next_task: '用“应用、风险、指标”重新讲一遍，不讲纯定义。',
  },
  {
    type: '英文追问',
    question: 'Why are you moving from design and hardware product work toward AI product roles?',
    framework: '压力追问',
    time_limit_seconds: 120,
    source_map: {
      personal: '个人资料库：职业背景与转型叙事',
      market: '岗位市场库：外企英文初筛问题',
      knowledge: '面试知识库：压力追问结构',
      real: '真实面试库：英文转型动机题',
    },
    next_task: '重录 60 秒英文版本，每句话控制在 15 个词以内。',
  },
  {
    type: '粤语轻量',
    question: '请用粤语或粤语夹中文，简单说明你为什么关注香港 / 深圳 / 广州的 AI 产品机会。',
    framework: 'STAR-LF',
    time_limit_seconds: 75,
    source_map: {
      personal: '个人资料库：目标城市偏好',
      market: '岗位市场库：粤港澳岗位地图',
      knowledge: '面试知识库：本地市场表达模板',
      real: '真实面试库：暂未命中真实粤语题',
    },
    next_task: '补录一个更自然的粤语开场，不追求完美，只保证能表达。',
  },
  {
    type: '压力问题',
    question: '你没有足够正式的 AI 产品经验，为什么我们还应该考虑你？',
    framework: '压力追问',
    time_limit_seconds: 120,
    source_map: {
      personal: '个人资料库：可迁移项目证据',
      market: '岗位市场库：AI 产品岗位门槛',
      knowledge: '面试知识库：承认-重构-证据-匹配',
      real: '真实面试库：短板追问题',
    },
    next_task: '把“短板解释”改成“风险已知 + 证据补偿”。',
  },
  {
    type: '行为面试',
    question: '请讲一次你在项目中推动别人改变想法的经历，重点说清楚冲突、行动和结果。',
    framework: 'STAR-LF',
    time_limit_seconds: 150,
    source_map: {
      personal: '个人资料库：跨职能协作经历',
      market: '岗位市场库：沟通与 stakeholder 管理要求',
      knowledge: '面试知识库：STAR-LF 行为面试',
      real: '真实面试库：团队协作题',
    },
    next_task: '补一个反方观点和你如何降低对方风险。',
  },
  {
    type: '反问练习',
    question: '请提出两个反问，用来判断团队成熟度和 AI 产品评估方式。',
    framework: '产品 Case',
    time_limit_seconds: 90,
    source_map: {
      personal: '个人资料库：求职限制与目标团队偏好',
      market: '岗位市场库：目标公司成熟度线索',
      knowledge: '面试知识库：高质量反问模板',
      real: '真实面试库：终面反问记录',
    },
    next_task: '准备 1 个产品评估反问和 1 个团队协作反问。',
  },
  {
    type: '产品 Case',
    question: '请为只有 7 天准备时间的候选人设计一个 AI 面试教练 MVP。',
    framework: '产品 Case',
    time_limit_seconds: 180,
    source_map: {
      personal: '个人资料库：Interview OS 项目设定',
      market: '岗位市场库：AI PM 对 MVP 和指标的要求',
      knowledge: '面试知识库：产品 Case 框架',
      real: '真实面试库：产品设计题',
    },
    next_task: '补一版 MVP 取舍，明确说出不做真实 API 的原因。',
  },
]

export const questionBank: QuestionBankItem[] = [
  {
    question_id: 'q_seed_001',
    user_id: seedUser.user_id,
    question_text: '请介绍一个项目，并说明它如何迁移到 AI 产品岗位。',
    normalized_question: '项目迁移到目标岗位',
    question_type: '项目深挖',
    source: '摸底',
    related_role_template: 'rt_ai_pm',
    related_project_id: 'project_seed_001',
    frequency: 3,
    difficulty: 3,
    user_performance_score: 58,
    priority_weight: 80,
  },
  {
    question_id: 'q_seed_002',
    user_id: seedUser.user_id,
    question_text: '你会如何评估一个 AI 功能是否真的有用？',
    normalized_question: 'AI 功能评估',
    question_type: 'AI / 产品知识',
    source: '练习',
    related_role_template: 'rt_ai_pm',
    related_project_id: 'project_seed_001',
    frequency: 2,
    difficulty: 4,
    user_performance_score: 61,
    priority_weight: 76,
  },
]

export const growthMap: GrowthMapItem[] = [
  {
    user_id: seedUser.user_id,
    skill_name: '职业定位',
    category: '策略',
    current_score: 68,
    target_score: 84,
    evidence_count: 4,
    latest_feedback: 'AI 产品方向更清楚了，但市场叙事还需要更锋利。',
    next_task: '为 AI 产品 / AIoT 岗位重写开场第一句话。',
  },
  {
    user_id: seedUser.user_id,
    skill_name: '项目叙事',
    category: '证据',
    current_score: 58,
    target_score: 86,
    evidence_count: 2,
    latest_feedback: '功能讲得多，用户问题和个人决策需要放到前面。',
    next_task: '用项目 7 步重建项目 1。',
  },
  {
    user_id: seedUser.user_id,
    skill_name: 'AI / 产品知识应用',
    category: '知识',
    current_score: 61,
    target_score: 85,
    evidence_count: 3,
    latest_feedback: '定义可以过关，但和岗位场景的连接还不够。',
    next_task: '用应用、风险和指标讲清楚 RAG。',
  },
  {
    user_id: seedUser.user_id,
    skill_name: '英文表达',
    category: '语言',
    current_score: 64,
    target_score: 82,
    evidence_count: 5,
    latest_feedback: '结构有了，但追问时句子需要更短、更稳。',
    next_task: '录一版 90 秒自我介绍和一个压力追问。',
  },
  {
    user_id: seedUser.user_id,
    skill_name: '压力追问处理',
    category: '面试',
    current_score: 59,
    target_score: 80,
    evidence_count: 1,
    latest_feedback: '回答解释了短板，但还没有把短板重构成岗位价值。',
    next_task: '练习“承认 - 重构 - 证据 - 匹配”结构。',
  },
]

export const vaultDocuments: VaultDocument[] = [
  {
    id: 'vault_user',
    type: '用户档案',
    title: '示例候选人档案',
    uploaded: true,
    pending_parse: false,
    parsed: true,
    indexed: true,
    used_in_generation: true,
    needs_update: false,
  },
  {
    id: 'vault_resume',
    type: '简历档案',
    title: 'AI 产品简历 v1',
    uploaded: true,
    pending_parse: false,
    parsed: true,
    indexed: true,
    used_in_generation: true,
    needs_update: false,
  },
  {
    id: 'vault_portfolio',
    type: '作品集档案',
    title: '作品集档案',
    uploaded: true,
    pending_parse: false,
    parsed: true,
    indexed: false,
    used_in_generation: true,
    needs_update: true,
  },
  {
    id: 'vault_project',
    type: '项目档案',
    title: '项目证据集',
    uploaded: true,
    pending_parse: false,
    parsed: true,
    indexed: true,
    used_in_generation: true,
    needs_update: true,
  },
  {
    id: 'vault_job_excel',
    type: '岗位市场库',
    title: 'Excel 岗位表与交互地图',
    uploaded: true,
    pending_parse: false,
    parsed: true,
    indexed: true,
    used_in_generation: true,
    needs_update: false,
  },
  {
    id: 'vault_training_media',
    type: '面试知识库',
    title: '教学视频 / 短视频 / 框架笔记',
    uploaded: true,
    pending_parse: true,
    parsed: false,
    indexed: false,
    used_in_generation: false,
    needs_update: true,
  },
  {
    id: 'vault_question_bank',
    type: '真实面试库',
    title: '真实录音、转写与模拟问题',
    uploaded: true,
    pending_parse: false,
    parsed: true,
    indexed: true,
    used_in_generation: true,
    needs_update: false,
  },
]

export const knowledgeDatabases: KnowledgeDatabase[] = [
  {
    id: 'personal_db',
    name: '个人资料库',
    purpose: '保存 CV、作品集、项目资料、自我介绍、项目讲稿、求职限制和语言状态。',
    sources: ['CV', '作品集 PDF', '作品集链接', '项目资料', '自我介绍', '项目讲稿', '求职限制', '语言状态'],
    status: '已索引，可用于摸底与训练',
    training_usage: '生成自我介绍、项目深挖、转型原因和岗位匹配题。',
  },
  {
    id: 'market_db',
    name: '岗位市场数据库',
    purpose: '保存 Excel 岗位表、交互地图、JD 和招聘链接。',
    sources: ['Excel 岗位表', '交互地图', 'JD', '招聘链接'],
    status: '已解析，可用于 A/B/C 岗位策略',
    training_usage: '为训练卡提供岗位高频要求、城市偏好和公司定向入口。',
  },
  {
    id: 'teaching_db',
    name: '面试知识/教学资料库',
    purpose: '保存面试教学视频、短视频、笔记、课程资料、STAR/宝洁八大问/项目七步法和 AI 产品面经。',
    sources: ['面试教学视频', '短视频/音频', '课程资料', 'STAR', '宝洁八大问', '项目七步法', 'AI 产品面经'],
    status: '部分待解析，当前使用模拟框架',
    training_usage: '为答案评分、框架反馈、追问和修正版提供依据。',
  },
  {
    id: 'real_interview_db',
    name: '真实面试数据库',
    purpose: '保存真实面试录音、真实面试转写、面试后记忆、面试官真实问题和面试结果。',
    sources: ['真实面试录音', '真实面试转写', '面试后补充记忆', '面试官真实问题', '面试结果'],
    status: '入口已就绪，当前用模拟记录反哺题库',
    training_usage: '让下一次模拟面试优先覆盖真实问过的问题。',
  },
]

export const uploadIntakeOptions: UploadIntakeOption[] = [
  {
    id: 'upload_cv',
    title: '上传 CV',
    description: '解析教育、经历、项目和岗位匹配证据。',
    target_database: '个人资料库',
    accepted: 'PDF / DOCX',
  },
  {
    id: 'upload_portfolio',
    title: '上传作品集 PDF / 粘贴作品集链接',
    description: '把作品集拆成项目证据、角色、结果和可追问点。',
    target_database: '个人资料库',
    accepted: 'PDF / URL',
  },
  {
    id: 'upload_project',
    title: '上传项目资料',
    description: '保存项目背景、决策、指标和反思，用于项目深挖训练。',
    target_database: '个人资料库',
    accepted: 'PDF / DOCX / 图片',
  },
  {
    id: 'upload_jobs',
    title: '上传 Excel 岗位表 / 交互地图',
    description: '解析岗位市场、高频要求、城市和 A/B/C 策略。',
    target_database: '岗位市场数据库',
    accepted: 'XLSX / HTML / CSV',
  },
  {
    id: 'upload_teaching',
    title: '上传面试教学资料',
    description: '导入课程、STAR、宝洁八大问、项目七步法和 AI 产品面经。',
    target_database: '面试知识/教学资料库',
    accepted: 'PDF / TXT / URL',
  },
  {
    id: 'upload_media',
    title: '上传短视频 / 音频',
    description: '后续接入语音识别与知识抽取，目前作为模拟待解析资料。',
    target_database: '面试知识/教学资料库',
    accepted: 'MP3 / MP4 / M4A',
  },
  {
    id: 'upload_real_recording',
    title: '上传真实面试录音',
    description: '生成转写、提取真实问题并反哺下一次模拟。',
    target_database: '真实面试数据库',
    accepted: 'MP3 / M4A / WAV',
  },
  {
    id: 'upload_real_transcript',
    title: '上传真实面试转写',
    description: '当没有录音或不能上传录音时，导入已授权的转写文本。',
    target_database: '真实面试数据库',
    accepted: 'TXT / MD / DOCX',
  },
]
